title: Welcome to Boyun's Blog
description: I'm trying to capture various daily stories.
baseurl: 
url: choiboyuna.github.io
author-name: Choi Boyun
author-image: 1.jpg
author-job: Baby Developer
author-email: choiboyuna@gmail.com
author-instagram: choiboyuun
about-author: >-
  I am a baby developer focusing on back-end development. Always hungry to keep
  learning.
social-twitter: null
social-facebook: null
social-github: choiboyuna
social-pinterest: null
social-instagram: choiboyuun
social-youtube: null
social-vk: null
social-linkedin: null
mailchimp: null
google-analytics: null
disqus-identifier: boyun
markdown: kramdown
permalink: '/:year/:month/:day/:title/'
plugins:
  - jekyll-paginate
paginate: 7
paginate_path: '/page/:num/'
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

jekyll_admin:
  hidden_links:
  homepage: "pages"
